name: CI/CD

on:
  push:
    branches:
      - main  # Запускать при пуше в основную ветку
      - develop  # Запускать при пуше в ветку develop
  pull_request:
    branches:
      - main  # Запускать на создание PR в основную ветку
      - develop  # Запускать на создание PR в ветку develop

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
        with: 
          fetch-depth: 0  # Загружаем все коммиты и теги
          
      - name: Fetch all tags
        run: git fetch --tags
        
      - name: Update version      
        run: |
          VERSION=$(git describe --tags --abbrev=0)
          if [ -f .env ]; then
            NEW_VERSION=$(grep '^VERSION=' .env | cut -d '=' -f 2)
            git tag $NEW_VERSION
            git push origin $NEW_VERSION  # Пушим новый тег в репозиторий
            echo "new version is $NEW_VERSION"
          fi

      # 7. Опционально: Вы можете добавить шаг для тестирования, например, если есть тесты, которые нужно выполнить в контейнерах
      # - name: Run tests
      #   run: |
      #     docker-compose exec <service_name> npm test
