name: Build and Push to GHCR

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ghcr.io/https://github.com/drondiz96/sra

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write  # Даём доступ к GHCR

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Log in to GHCR
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and Push Backend
      uses: docker/build-push-action@v4
      with:
        context: ./backend
        tags: |
          ${{ env.IMAGE_NAME }}-backend:latest
          ${{ env.IMAGE_NAME }}-backend:${{ github.sha }}
        push: true

    - name: Build and Push ML Service
      uses: docker/build-push-action@v4
      with:
        context: ./ml-service
        tags: |
          ${{ env.IMAGE_NAME }}-ml-service:latest
          ${{ env.IMAGE_NAME }}-ml-service:${{ github.sha }}
        push: true