name: Release

on:
  push:
    branches:
      - main  # Работает при push в основную ветку (можно изменить на вашу)

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Git
      uses: actions/setup-git@v2
      with:
        user-name: "github-actions"
        user-email: "github-actions@github.com"

    - name: Get current version
      id: version
      run: |
        VERSION=$(git describe --tags --abbrev=0)
        echo "Current version: $VERSION"
        echo "::set-output name=version::$VERSION"

    - name: Bump version
      id: bump_version
      run: |
        NEW_VERSION=$(echo ${{ steps.version.outputs.version }} | awk -F. -v OFS=. '{$NF++;print}')
        echo "New version: $NEW_VERSION"
        echo "::set-output name=new_version::$NEW_VERSION"

    - name: Create new tag
      run: |
        git tag ${{ steps.bump_version.outputs.new_version }}
        git push origin ${{ steps.bump_version.outputs.new_version }}

    - name: Create GitHub release
      run: |
        gh release create ${{ steps.bump_version.outputs.new_version }} --notes "Release ${{ steps.bump_version.outputs.new_version }}"
