version: '3.8'  # Версия Docker Compose

services:
  frontend:
    build:
      context: ./frontend
    ports:
      # - "8090:80"
     - "80:80"
     - "443:443"
    container_name: front
    restart: unless-stopped

volumes:
  postgres_data:  # Определяем том для хранения данных
