spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/bip
    username: develop
    password: develop
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  mail:
    host: smtp.mail.ru
    port: 465
    username: karzhavin.danil@mail.ru
    password: ${BIP_SMTP_MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true  # Включаем SSL
          starttls:
            enable: false # STARTTLS не нужен, так как используем SSL




server:
  address: localhost
  port: 8080

management:
  server:
    port: 8081 # Actuator работает на отдельном порту
  security:
    enabled: false  # Если нужно отключить безопасность для актюаторов
  endpoints:
    web:
      exposure:
        include: "*"  # Разрешить доступ ко всем эндпоинтам
  endpoint:
    mappings:
      enabled: true  # Включить эндпоинт mappings, который показывает все доступные маршруты
