spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/bip
    username: develop
    password: develop
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  mail:
    host: smtp.gmail.com
    port: 587  # Gmail использует 587 для STARTTLS, 465 для SSL
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD} # Храним пароль в переменной среды
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: false  # SSL отключаем, так как используем STARTTLS
          starttls:
            enable: true  # Для Gmail обязательно включить STARTTLS
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${CLIENT_ID}
            client-secret: ${CLIENT_SECRET}
            scope: profile,email




server:
  address: localhost
  port: 8080

management:
  server:
    port: 8081 # Actuator работает на отдельном порту
  security:
    enabled: false  # Если нужно отключить безопасность для актюаторов
  endpoints:
    web:
      exposure:
        include: "*"  # Разрешить доступ ко всем эндпоинтам
  endpoint:
    mappings:
      enabled: true  # Включить эндпоинт mappings, который показывает все доступные маршруты
