spring:
  datasource:
    username: develop
    password: develop
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: false
          starttls:
            enable: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 461804719965-roubsl8r43ob7atq19p6ut4v1upg2mrj.apps.googleusercontent.com
            client-secret: ${CLIENT_SECRET}
            redirect-uri: "http://localhost:8080/login/oauth2/code/google"
            scope:
              - profile
              - email
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
            user-name-attribute: email

server:
  port: 8080

management:
  server:
    port: 8081
  security:
    enabled: false
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    mappings:
      enabled: true
